### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by 1kimli2** [Hope-Rita/PatCLS#1]
请问：scipy,numpy,gensim,dgl安装什么版本的呢

**Comment by Hope-Rita** [comment]
你好，scipy是1.9.1，numpy是1.22.3，gensim是3.8.3，dgl是0.8.0。

**Comment by 1kimli2** [comment]
好的，谢谢，但我安装包的时候还出现一些问题，请问Python版本是多少，能不能给我个requirement.txt文件把所有需要用到包的版本写进去呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月12日(周三) 下午5:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hope-Rita/PatCLS] 版本问题 (Issue #1)




 
你好，scipy是1.9.1，numpy是1.22.3，gensim是3.8.3，dgl是0.8.0。

**Comment by Hope-Rita** [comment]
[requirements.txt](https://github.com/user-attachments/files/15916639/requirements.txt)
因为其他任务也用到了该环境，所以requirements.txt中有些package这个项目没有用上，请查收。
