### ISSUE TITLE
几个参数的问题

### ISSUE THREAD

**Issue by 1kimli2** [Hope-Rita/PatCLS#2]
配置参数：

参数use_lstm_text 和参数model_way还有PatentCLS模块下的AttentionDNY类的属性值use_hierarchy填写什么？

model_way应该填‘gcn' 其他两个我分别试了True和False都出现了bug请问为什么

**Comment by Hope-Rita** [comment]
use_hierarchy是True,use_lstm_text是False，我之后会上传新的param_parser.py文件
