### ISSUE TITLE
运行时的一些bug

### ISSUE THREAD

**Issue by 1kimli2** [Hope-Rita/PatCLS#3]
[配置参数.txt](https://github.com/user-attachments/files/15928634/default.txt)

这是我按论文的配置参数，论文中没有就按的默认参数，加上use_hierarchy是True,use_lstm_text是False，最后在模型训练时代码报错
 assert res_emb.shape == torch.Size([B, self.embedding_label])这个报错是AttentionDNY中的DynamicGraph类中。res_emb.shape=[32,608],B=32,self.embedding_label=1024,两个形状不同，请问是参数填写的不对吗？还是其他原因。

**Comment by Hope-Rita** [comment]
参数是没问题的，res_emb维度没有问题，这个assert我后来给删掉了，抱歉。我现在上传了新的一版代码，修复了您之前说的问题，您再看看。
